version: "3.3"
services:
  minio:
    image: bitnami/minio:latest
    environment:
      MINIO_ACCESS_KEY: "access-mock-key"
      MINIO_SECRET_KEY: "secret-mock-key"
      MINIO_PORT_NUMBER: 9000
    ports:
    - 9000:9000
