#!/bin/bash

make clean
./semantic-release --ghr -f --changelog tmpChangelog.md
if [[ "$?" == 65 ]]; then
  echo "No changes"
  exit 0
fi
cat tmpChangelog.md CHANGELOG.md > newChangelog.md
rm -fr tmpChangelog.md
mv newChangelog.md CHANGELOG.md
export VERSION=$(cat .version)
make update-version-go

make build-all
ghr $(cat .ghr) build/

git config --global user.email "ci@github.com"
git config --global user.name "Github actions"
git add .
git commit -m 'chore(bump): version [skip ci]'
git push --follow-tags
